version: "3"
services:
  mongodb:
    build: ./mongodb
    ports:
      - "27017:27017"
    restart: always
    # volumes:
    # - ./mongodb:/docker-entrypoint-initdb.d:ro,z
  #    networks:
  #      default_bridge:
  #        ipv4_address: 172.16.1.3
  mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    restart: always
  #    networks:
  #      default_bridge:
  #        ipv4_address: 172.16.1.2

  mygrang:
    build: ./mygrang
    depends_on:
      - mysql
    ports:
      - "8090:8090"
    restart: always
  #    networks:
  #      default_bridge:
  #        ipv4_address: 172.16.1.4
  chatapp:
    build: ./chatapp
    ports:
      - "8100:8100"
    restart: always
#    networks:
#      default_bridge:
#        ipv4_address: 172.16.1.5
#    networks:
#      - my-network

#networks:
#  default_bridge:
#    ipam:
#      driver: default
#      config:
#        - subnet: 172.16.1.0/24
