#!/bin/bash
if ps -ef | grep -v grep | grep ngrok > /dev/null; then
  ps -ef | grep ngrok | awk '{print $2}' | xargs kill -9
  echo "ngrok restart"
  sleep 5
else
  echo "ngrok is not running"
fi

ngrok http 8080 > /dev/null &
sleep 10
ngrok_url="$(curl -sL http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')"

my_name="ssuperj"
my_token="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"

repositories=$(curl -H "Authorization: token ${my_token}" https://api.github.com/users/${my_name}/repos | jq -r '.[].name | select(. | startswith("docker-"))')

echo ${repositories}
for repo in ${repositories}
do
  hook_id=$(curl -H "Authorization: token ${my_token}" https://api.github.com/repos/${my_name}/${repo}/hooks | jq -r '.[] .id')
if [ ! -z "$hook_id" ]; then
  curl -X PATCH -H "Authorization: token ${my_token}" -H "Content-Type: application/json" https://api.github.com/repos/${my_name}/${repo}/hooks/${hook_id} -d '{"config": {"url": "'${ngrok_url}/github-webhook/'"}}'
fi
done