server:
  port: 8090
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  devtools:
    restart:
      enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/my_db?useSSL=false&allowPublicKeyRetrieval=true
    username: poqwer95
    password: 1234
#    url: jdbc:mysql://{MY_IP_ADDRESS}:3306/my_db?useSSL=false&allowPublicKeyRetrieval=true

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true
  #      hibernate.globally_guoted_identifiers: true

  jackson:
    serialization:
      fail-on-empty-beans: false
