spring:
    mvc:
        view:
            prefix: /WEB-INF/views/
            suffix: .jsp
    devtools:
        restart:
            enabled: false
    jpa:
        open-in-view: true
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            use-new-id-generator-mappings: false
        show-sql: true
        properties:
            hibernate.format_sql: true
    jackson:
        serialization:
            fail-on-empty-beans: false

server:
    port: 80
    servlet:
        context-path: /
        encoding:
            charset: UTF-8
            enabled: true
            force: true
